# Generated by Django 5.1.5 on 2025-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmHouse_Website', '0005_alter_reviews_bookingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dishCategory',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='menu',
            name='dishSource',
            field=models.CharField(default='', max_length=30),
        ),
    ]
