# Generated by Django 5.1.5 on 2025-06-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmHouse_Website', '0006_menu_dishcategory_menu_dishsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reviewTitle',
            field=models.CharField(default='', max_length=50),
        ),
    ]
