# Generated by Django 5.1.5 on 2025-07-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmHouse_Website', '0007_reviews_reviewtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='IDimage',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='IDnumber',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='IDtype',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='paymentStatus',
            field=models.CharField(default='', max_length=10),
        ),
    ]
